version: '3.7'

services:
    api:
        image: nycflights/nycflights-api:test
        container_name: nyc-flights13-api
        ports:
            - '8080:80'
        depends_on:
            - grpc_service
        links:
            - 'grpc_service'
        environment:
            'GRPC_SERVER_HOST': 'grpc_service'
            'GRPC_SERVER_PORT': '80'
            'GRPC_SERVER_PROTOCOL': 'http'
        networks: 
            - 'front_default'

    grpc_service:
        image: nycflights/nycflights-data-grpc:test
        container_name: nyc-flights13-grpc
        hostname: grpc_service
        environment:
            'DATABASE_USERNAME': 'nycflightsadmin@nycflights-postgresql'
            'DATABASE_PASSWORD': 'flights13!'
            'DATABASE_SERVER': 'nycflights-postgresql.postgres.database.azure.com'
            'DATABASE_PORT': '5432'
            'DATABASE_NAME': 'nycflights'
        networks: 
            - 'front_default'

networks:
    front_default: